TAS-103/Ajouter une nouvelle carte
a-little-byte/web-deprecated pull request #20
Opened 2024-10-22 11:55 UTC by Brendan-bx

2024-10-22 11:59 UTC, Limerio requested changes

2024-10-22 11:59 UTC, Limerio commented on apps/api/src/routes/users/creditCards.ts
> +		})
remove those lines

2024-10-22 11:59 UTC, Limerio commented on apps/api/src/routes/users/creditCards.ts
> +				return c.json(newCreditCard, 201)
There is a problem with your query.
I'm not sure if the user exists or not. Use the param `:userId` to check if the user exists

2024-10-22 12:08 UTC, WookiesRpeople2 submitted a review, later dismissed

2024-10-22 12:10 UTC, Limerio commented on apps/api/src/routes/users.ts
> +		creditCardRouter(),
Add a middleware to check if the connected user id is equal to the userId param 
```suggestion
                isLoginUser,
		creditCardRouter(),
```

2024-10-23 09:29 UTC, Limerio requested changes

2024-10-23 09:29 UTC, Limerio commented on apps/admin/package.json
> +		"autoprefixer": "^10.4.20",
remove this line
```suggestion
```

2024-10-23 09:29 UTC, Limerio commented on apps/api/src/middlewares/isUserEqualtoUserLogin.ts
> +		return json({ error: "Forbidden" }, 403)
magic number 🌟
take a look at the `HTTP_STATUS_CODES` and use one of these values

2024-10-23 09:29 UTC, Limerio commented on apps/api/src/routes/users/creditCards.ts
> +				return c.json(newCreditCard, 201)
magic number 🌟
take a look at the `HTTP_STATUS_CODES` and use one of these values

2024-10-23 09:29 UTC, Limerio commented on apps/api/src/routes/users/creditCards.ts
> +				return c.json({ error: "Failed to create credit card" }, 500)
magic number 🌟
take a look at the `HTTP_STATUS_CODES` and use one of these values

2024-10-23 09:29 UTC, Limerio commented on apps/landing/vite.config.ts.timestamp-1729632290581-391b06fb3d405.mjs
remove this file

2024-10-23 09:29 UTC, Limerio commented on packages/common/src/validators.ts
> +export const cvvCodeValidator = z.string().min(3).max(3)
moove it on the bottom on the file

2024-10-23 09:42 UTC, Limerio approved these changes

2024-10-23 09:48 UTC, merged